parameters:
    yaroslav_json_mapper.default_adapter.class: Yaroslav\JsonMapperBundle\Adapter\AnyAdapter
    yaroslav_json_mapper.json_mapper.class: Yaroslav\JsonMapperBundle\Mapper\JsonMapper
services:
    yaroslav_json_mapper.default_adapter:
        class: "%yaroslav_json_mapper.default_adapter.class%"
